# Generated by Django 3.0.4 on 2020-04-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0004_auto_20200411_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
