# Generated by Django 3.0.4 on 2020-03-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CombinedElements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
