# Generated by Django 3.0.4 on 2020-03-20 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CombinedElements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('color', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('manufacturer', models.TextField()),
                ('description', models.TextField()),
                ('picture', models.ImageField(default='products/default.jpg', upload_to='products')),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CombinedElements.Category')),
            ],
        ),
    ]
