# Generated by Django 3.0.4 on 2020-03-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20200320_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='full_description',
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='Good Product'),
            preserve_default=False,
        ),
    ]
