# Generated by Django 3.0.4 on 2020-03-21 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20200321_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to='products')),
                ('image2', models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to='products')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.Product')),
            ],
        ),
    ]
