# Generated by Django 3.0.4 on 2020-04-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='zebraa-products'),
        ),
    ]
